image: registry.gitlab.com/prabh-t/ingest-deploy:0.1

before_script:
  - echo "Updating ingest-kube-deployment"
  - cd /home/ingest/ingest-kube-deployment && git pull

stages:
  - deploy

deploy_ingest:
  stage: deploy
  script:
    - >
      if [[ "$ENV" =~ ^(dev|integration|staging|prod)$ ]]; then
        echo "Deploying on $ENV"
        kubectl config set-context ingest-eks-$ENV
        source config/environment_$ENV
        cd apps
        for APP in ${APPS}; do make deploy-app-${APP}; done
      fi
  when: manual